# Generated by Django 3.2.7 on 2021-09-14 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloodProneArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField(default=0.001)),
            ],
            options={
                'db_table': 'flood_prone_area',
            },
        ),
        migrations.CreateModel(
            name='FloodLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rain_level', models.IntegerField()),
                ('flood_level', models.IntegerField()),
                ('floodstart', models.IntegerField()),
                ('fpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.floodpronearea')),
            ],
        ),
    ]
