# Generated by Django 3.2.7 on 2021-09-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floodpronearea',
            name='radius',
            field=models.FloatField(default=100),
        ),
    ]
